### ISSUE TITLE
Erro favoritos

### ISSUE THREAD

**Issue by HelArcherix** [mrpiracyPT/repository.mrpiracy#7]
Já testei em android, windows e raspberry pi e obtenho sempre este problema, não consigo adicionar nada aos favoritos

No primeiro screenshot aparecem duas vez adicionar aos favoritos
![screenshot_20181105-185816](https://user-images.githubusercontent.com/44784335/48020282-7ce59a00-e12d-11e8-8eb6-0201df98e7b0.jpg)

Se clicar no texto em português dá erro 
![screenshot_20181105-185821 1](https://user-images.githubusercontent.com/44784335/48020303-8a028900-e12d-11e8-8c89-f892dab8f273.jpg)

Se clicar no texto em inglês (add to favorites), teoricamente ficaria, mas não surge nada marcado na area pessoal como favorito.

No log do Kodi, não me aparece erro nenhum.

Continuação de um bom trabalho ;)
Abraço

**Comment by luisfbmelo** [comment]
A mim também surge esse erro. No log aparece o seguinte:

```
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: (0,)
 Traceback (most recent call last):
 File "/storage/.kodi/addons/plugin.video.mrpiracy/addon.py", line 60, in <module> mrpiracy.mrpiracy().adicionarFavoritos(url)
File "/storage/.kodi/addons/plugin.video.mrpiracy/resources/lib/mrpiracy.py", line 1585, in adicionarFavoritos
resultado = json.loads(resultado)[0]
KeyError: (0,)
-->End of Python script error report<--
```
